USE C:\DBASE\PAGINA1.DBF
BROWSE TITLE "PULSE <ESCAPE> PARA CONTINUAR LEYENDO LA SIGUIENTE PAGINA"

USE C:\DBASE\PAGINA2.DBF
BROWSE TITLE "PULSE <ESCAPE> PARA CONTINUAR LEYENDO LA SIGUIENTE PAGINA"

USE C:\DBASE\PAGINA3.DBF
BROWSE TITLE "PULSE <ESCAPE> PARA CONTINUAR LEYENDO LA SIGUIENTE PAGINA"

*** CONTINUA . . .
